version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    target-branch: master
    groups:
      minor-patch-updates:
        update-types: [ "patch", "minor" ]

    labels:
      - dependencies
